[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --html=reports/report.html --self-contained-html
markers =
    smoke: smoke test suite
    regression: full regression suite
    login: login related tests
    cart: shopping cart tests
    tempTest: temporary cart tests
    unit: unit tests
    product: unit test for products
    productregression: unit test for products-regression testcases